# Generated by Django 5.1.3 on 2024-12-05 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportticket',
            name='email',
            field=models.EmailField(default='1', help_text='Email to respond to the user', max_length=254),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Response',
        ),
    ]
