# Generated by Django 5.1.3 on 2024-12-05 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0002_supportticket_email_delete_response'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportticket',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
