# Generated by Django 5.1.3 on 2024-12-09 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0003_alter_supportticket_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supportticket',
            options={'permissions': [('can_resolve_tickets', 'Can resolve tickets')]},
        ),
    ]
