# Generated by Django 5.1.3 on 2024-12-03 20:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='in_stock',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0, message='You need to enter a numer higher than 0!')]),
        ),
        migrations.AlterField(
            model_name='product',
            name='rating',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5, message="You can't exceed the value of 5!")]),
        ),
    ]
