# Generated by Django 5.1.3 on 2024-12-11 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appprofile',
            name='active_profile',
            field=models.BooleanField(default=False),
        ),
    ]
