# Generated by Django 5.1.3 on 2024-12-11 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_appprofile_active_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appprofile',
            name='age',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='appprofile',
            name='first_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='appprofile',
            name='height',
            field=models.FloatField(help_text='Height in cm', null=True),
        ),
        migrations.AlterField(
            model_name='appprofile',
            name='last_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='appprofile',
            name='weight',
            field=models.FloatField(help_text='Weight in kg', null=True),
        ),
    ]
