name: Django CI/CD to Render

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Django checks
        run: |
          python manage.py check

      - name: Collect static files
        env:
          DJANGO_SETTINGS_MODULE: fitnessEcommerceApp.settings
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          DEBUG: False
          DATABASE_URL: ${{ secrets.DATABASE_URL }}  # Add this line
        run: |
          python manage.py collectstatic --noinput --clear

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: collected-static
          path: staticfiles/

  deploy:
    runs-on: ubuntu-latest
    needs: build  # <-- waits until build job finishes

    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: collected-static
          path: staticfiles/

      - name: Deploy to Render
        run: |
          curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK }}

